Client_TicketPremium_Rest/Client_TicketPremium/Models/Bill.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Client_TicketPremiun.Models
{
    public class Bill
    {
        public string code_client { get; set; }
        public string name_client { get; set; }
        public int code_bill { get; set; }
        public string date_bill { get; set; }
        public string way_pay { get; set; }
        public SoccerGame soccer_game { get; set; }
        public float total { get; set; }
    }
}

Client_TicketPremium_Rest/Client_TicketPremium/Controllers/BillsController.cs
using Client_TicketPremiun.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Newtonsoft.Json;
using System.Net.Http;
using System.Threading.Tasks;


namespace Client_TicketPremium.Controllers
{
    public class BillsController : Controller
    {
        // GET: Bills
        public async Task<ActionResult> Buy()
        {
            string ip = "192.168.1.114";
            var httpClient = new HttpClient();
            string codeSoccerGame = Request["code"];

            string urlEnviada = "http://" + ip + ":8080/TicketPremium_Server_REST/WSTicket/getSoccerGame/"+codeSoccerGame;
            var json = await httpClient.GetStreamAsync(urlEnviada);
            SoccerGame soccerGame = JsonConvert.DeserializeObject<SoccerGame>(json.ToString());

            string urlEnviada2 = "http://" + ip + ":8080/TicketPremium_Server_REST/WSTicket/getClients/";
            var json2 = await httpClient.GetStreamAsync(urlEnviada2);
            List<Client> clientList = JsonConvert.DeserializeObject<List<Client>>(json2.ToString());

            ViewBag.clients = new SelectList(clientList, "code_client", "name_client");
            ViewBag.code = soccerGame.code_soccergame;
            return View(soccerGame);

        }

        [HttpPost]
        public async Task<ActionResult> Bill()
        {
            string codeClient = Request["clients"];
            string codePayway = Request["payway"];
            int quantityGeneral = 0;
            int quantityPalco = 0;
            int quantityTribuna = 0;
            if (Int32.TryParse(Request["GENERAL"], out int auxGeneral))
            {
                quantityGeneral = auxGeneral;
            }
            if (Int32.TryParse(Request["PALCO"], out int auxPalco))
            {
                quantityPalco = auxPalco;
            }
            if (Int32.TryParse(Request["TRIBUNA"], out int auxTribuna))
            {
                quantityTribuna = auxTribuna;
            }

            string codeSoccerGame = Request["code"];
            string ip = "192.168.1.114";
            var httpClient = new HttpClient();

            string urlEnviada = "http://" + ip + ":8080/TicketPremium_Server_REST/WSTicket/getSoccerGame/" + codeSoccerGame;
            var json = await httpClient.GetStreamAsync(urlEnviada);
            SoccerGame soccerGame = JsonConvert.DeserializeObject<SoccerGame>(json.ToString());
            List<Locality> listLocalities = soccerGame.localities.ToList();

            foreach (Locality l in listLocalities)
            {
                if (l.code_locality.Equals("GENERAL"))
                {
                    l.availability = quantityGeneral;
                }
                if (l.code_locality.Equals("PALCO"))
                {
                    l.availability = quantityPalco;
                }
                if (l.code_locality.Equals("TRIBUNA"))
                {
                    l.availability = quantityTribuna;
                }
            }

            string urlEnviada2 = "http://" + ip + ":8080/TicketPremium_Server_REST/WSTicket/updateLocalitiesSoccerGame/";

            HttpClient client = new HttpClient();


            Bill billCreated = await httpClient.PostAsync("AddNewArticle", new SoccerGame
            {
                code_soccergame = "",
                code_payway=codePayway,
                localities = listLocalities
            });

            float subTotal = billCreated.total/1.12f;
            ViewBag.subtotal = subTotal;
            ViewBag.iva = billCreated.total-subTotal;
            return View(billCreated);
 
        }

    }
}

Client_TicketPremium_Rest/Client_TicketPremium/Views/Bills/Bill.cshtml
<!DOCTYPE html>

@model Client_TicketPremium.WSTicket.Bill

@{
    ViewBag.Title = "Bill";
}

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Factura</title>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="~/Scripts/script.js" type="text/javascript"></script>
</head>
<body>
    <div class="wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="pull-left">Cabecera</h2>
                    <br>
                    <label class="form-control">Partido: &#09; @Model.soccer_game.local_team VS @Model.soccer_game.visitor_team</label>
                    <label class="form-control">Fecha: &#09; @Model.soccer_game.date_soccergame</label>
                    <label class="form-control">Cliente: &#09; @Model.name_client</label>
                    <label class="form-control">Forma de pago: &#09; @Model.way_pay </label>
                    <br />
                    <div class="page-header">
                        <h2>Localidades</h2>
                    </div>
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Nombre localidad</th>
                                <th>Comprados</th>
                                <th>Precio</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var localitie in Model.soccer_game.localities)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => localitie.code_locality)</td>
                                    <td>@Html.DisplayFor(modelItem => localitie.availability)</td>
                                    <td>@Html.DisplayFor(modelItem => localitie.price)</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <br />
                    <label class="form-control">Total: &#09; @Model.total </label>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Client_TicketPremium_Rest/Client_TicketPremium/Views/Bills/Buy.cshtml
<!DOCTYPE html>

@model Client_TicketPremium.WSTicket.SoccerGame

@{
    ViewBag.Title = "Buy";
}


<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Factura</title>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="~/Scripts/script.js" type="text/javascript"></script>
</head>
<body>
    <div class="wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    @using (Html.BeginForm("Bill", "Bills", FormMethod.Post))
                    {
                        <h2 class="pull-left">Cabecera</h2>
                        <br>
                        <label class="form-control">Partido: &#09; @Model.local_team VS @Model.visitor_team</label>
                        <label class="form-control">Fecha: &#09; @Model.date_soccergame</label>
                        <label class="form-control">Cliente: &#09; @Html.DropDownList("clients")</label>
                        <label class="form-control">
                            Forma de pago: &#09;
                            <select name="payway" id="payway">
                                <option value="Tarjeta de crédito">Tarjeta de crédito</option>
                                <option value="Transferencia electrónica">Transferencia electrónica</option>
                                <option value="PayPal">PayPal</option>
                            </select>
                        </label>
                        <br />
                        <div class="page-header">
                            <h2>Localidades</h2>
                        </div>
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nombre localidad</th>
                                    <th>Disponibles</th>
                                    <th>Precio</th>
                                    <th>Cantidad</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var localitie in Model.localities)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => localitie.code_locality)</td>
                                        <td>@Html.DisplayFor(modelItem => localitie.availability)</td>
                                        <td>@Html.DisplayFor(modelItem => localitie.price)</td>
                                        <td>
                                            <input type="text" pattern="[0-9]+" min="0" max="@localitie.availability" name="@localitie.code_locality" id="@localitie.code_locality" />
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        <br />
                        <input type="hidden" id="code" name="code" value="@ViewBag.code" />
                        <input type="submit" class="btn btn-primary" value="Finalizar compra" />
                        <a href="~/SoccerGames/SoccerGames" class="btn btn-primary">Cancelar</a>
                    }
                </div>
            </div>
        </div>
    </div>
</body>
</html>